### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph-ontomatcher#1]
@jnguyenx @ccondit having issues just getting my initial setup organized. The test attempts to load a pizza graph and create a vocabulary object but I'm lacking guice-fu

**Comment by ccondit** [comment]
Added an graph loading junit rule which I think will be helpful throughout the code base:
https://github.com/SciGraph/SciGraph/commit/3cd98cc113d4c7259515d6828171acc3495529ed

Let's discuss your specific use case this afternoon...

/cc @jnguyenx

**Comment by cmungall** [comment]
Progress report:

Able to iterate through all nodes, getting all property values for each an calling EntityProcesses

however, the number of annotations is always zero

I suspect it's because I need to do the equivalent of this in java:

```
graphConfiguration:
    ...
    indexedNodeProperties:
      - category
      - label
      - fragment
    exactNodeProperties:
      - label
      - synonym
      - definition

...

mappedProperties:
  - name: label # The name of the new property
    properties: # The list of properties mapped to the new property
    - http://www.w3.org/2000/01/rdf-schema#label
    - http://www.w3.org/2004/02/skos/core#prefLabel
...
```

I started playing with OntologyGraphRule, adding the following:

```
    List<MappedProperty> mappedProps = new ArrayList<>();
    MappedProperty mp = new MappedProperty("label");
    mp.setProperties(Collections.singletonList("http://www.w3.org/2000/01/rdf-schema#label"));
	mappedProps.add(mp);
	GraphOwlVisitor visitor = new GraphOwlVisitor(walker, graph, mappedProps);
```

This had the effect of setting the convenience label node, but I think I need something like `indexedNodeProperties` to make it recognizable by the EA, but not sure if core OntologyGraphRule is the way to config this
